"""APEX - The last coding agent you'll ever need."""

__version__ = "2.0.0"
__author__ = "APEX Team"

# Core config — always available (no heavy deps)
from .config import MODEL_PROVIDERS, MODELS, SYSTEM_PROMPT, Config


def __getattr__(name):
    """Lazy-load heavy submodules only when accessed."""
    _lazy_modules = {
        "Agent": (".agent", "Agent"),
        "ToolExecutor": (".tools", "ToolExecutor"),
        "AsyncToolExecutor": (".tools", "AsyncToolExecutor"),
        "TOOL_SCHEMAS": (".tools", "TOOL_SCHEMAS"),
        "UI": (".ui", "UI"),
        "SessionManager": (".session", "SessionManager"),
        "UndoManager": (".session", "UndoManager"),
        "Memory": (".memory", "Memory"),
        "get_repo_map": (".context", "get_repo_map"),
        "agent_manager": (".agents", "agent_manager"),
        "AgentConfig": (".agents", "AgentConfig"),
        "BUILTIN_AGENTS": (".agents", "BUILTIN_AGENTS"),
        "MCPManager": (".mcp", "MCPManager"),
        "MCPClient": (".mcp", "MCPClient"),
        "MCPServerConfig": (".mcp", "MCPServerConfig"),
        "mcp_manager": (".mcp", "mcp_manager"),
        "load_mcp_config": (".mcp", "load_mcp_config"),
        "ContextWindow": (".context_manager", "ContextWindow"),
        "ConversationManager": (".context_manager", "ConversationManager"),
        "AutoSaveManager": (".context_manager", "AutoSaveManager"),
        "CodeSandbox": (".sandbox", "CodeSandbox"),
        "ShellSession": (".sandbox", "ShellSession"),
        "sandbox": (".sandbox", "sandbox"),
        "PluginManager": (".plugins", "PluginManager"),
        "PluginBase": (".plugins", "PluginBase"),
        "plugin_manager": (".plugins", "plugin_manager"),
        "load_plugins_from_config": (".plugins", "load_plugins_from_config"),
        "logger": (".telemetry", "logger"),
        "perf_monitor": (".telemetry", "perf_monitor"),
        "Logger": (".telemetry", "Logger"),
        "PerformanceMonitor": (".telemetry", "PerformanceMonitor"),
        "custom_tool_manager": (".config_tools", "custom_tool_manager"),
        "CustomToolManager": (".config_tools", "CustomToolManager"),
        "load_custom_tools": (".config_tools", "load_custom_tools"),
        "workspace_manager": (".workspace", "workspace_manager"),
        "WorkspaceManager": (".workspace", "WorkspaceManager"),
        "WorkspaceContext": (".workspace", "WorkspaceContext"),
        "GitContext": (".workspace", "GitContext"),
        "LSPManager": (".lsp", "LSPManager"),
        "get_lsp_manager": (".lsp", "get_lsp_manager"),
        "CommandManager": (".commands", "CommandManager"),
        "get_command_manager": (".commands", "get_command_manager"),
        "PlanApproval": (".commands", "PlanApproval"),
        "ProjectInitializer": (".project", "ProjectInitializer"),
        "FileWatcher": (".project", "FileWatcher"),
        "get_project_initializer": (".project", "get_project_initializer"),
        "SlashCommandManager": (".slash", "SlashCommandManager"),
        "get_slash_command_manager": (".slash", "get_slash_command_manager"),
        "MentionParser": (".mentions", "MentionParser"),
        "get_mention_parser": (".mentions", "get_mention_parser"),
        "get_file_completer": (".mentions", "get_file_completer"),
        "SkillManager": (".skills", "SkillManager"),
        "get_skill_manager": (".skills", "get_skill_manager"),
        "DiffTool": (".skills", "DiffTool"),
        "SearchReplace": (".skills", "SearchReplace"),
        "CodeAnalyzer": (".skills", "CodeAnalyzer"),
        "RetryHandler": (".advanced", "RetryHandler"),
        "BatchOperation": (".advanced", "BatchOperation"),
        "StreamingOutput": (".advanced", "StreamingOutput"),
        "ToolTimeout": (".advanced", "ToolTimeout"),
        "ContextOptimizer": (".advanced", "ContextOptimizer"),
        "FileOperationCache": (".advanced", "FileOperationCache"),
        "get_retry_handler": (".advanced", "get_retry_handler"),
        "get_file_cache": (".advanced", "get_file_cache"),
        "ShellExpander": (".extras", "ShellExpander"),
        "EnvManager": (".extras", "EnvManager"),
        "TaskQueue": (".extras", "TaskQueue"),
        "HistorySearch": (".extras", "HistorySearch"),
        "WorkspaceValidator": (".extras", "WorkspaceValidator"),
        "SecurityAuditor": (".extras", "SecurityAuditor"),
        "get_env_manager": (".extras", "get_env_manager"),
        "get_task_queue": (".extras", "get_task_queue"),
        "get_history_search": (".extras", "get_history_search"),
        "CodeRefactorer": (".codegen", "CodeRefactorer"),
        "DatabaseManager": (".codegen", "DatabaseManager"),
        "DockerManager": (".codegen", "DockerManager"),
        "APIClientGenerator": (".codegen", "APIClientGenerator"),
        "DocumentationGenerator": (".codegen", "DocumentationGenerator"),
        "PerformanceProfiler": (".codegen", "PerformanceProfiler"),
        "apex_config": (".config_v2", "apex_config"),
        "tui_config": (".config_v2", "tui_config"),
        "ApexConfig": (".config_v2", "ApexConfig"),
        "TuiConfig": (".config_v2", "TuiConfig"),
        "theme_manager": (".theme_manager", "theme_manager"),
        "ThemeManager": (".theme_manager", "ThemeManager"),
        "share_manager": (".share", "share_manager"),
        "ShareManager": (".share", "ShareManager"),
        "formatter_manager": (".formatter", "formatter_manager"),
        "FormatterManager": (".formatter", "FormatterManager"),
        "watcher": (".watcher", "watcher"),
        "commands_manager": (".commands_manager", "commands_manager"),
        "CustomCommandManager": (".commands_manager", "CustomCommandManager"),
        "CommandConfig": (".commands_manager", "CommandConfig"),
    }
    if name in _lazy_modules:
        import importlib

        module_path, attr = _lazy_modules[name]
        module = importlib.import_module(module_path, __name__)
        return getattr(module, attr)
    raise AttributeError(f"module 'apex' has no attribute {name!r}")


__all__ = [
    "BUILTIN_AGENTS",
    "MODELS",
    "MODEL_PROVIDERS",
    "SYSTEM_PROMPT",
    "TOOL_SCHEMAS",
    "UI",
    "APIClientGenerator",
    "Agent",
    "AgentConfig",
    "ApexConfig",
    "AsyncToolExecutor",
    "AutoSaveManager",
    "BatchOperation",
    "CodeAnalyzer",
    "CodeRefactorer",
    "CodeSandbox",
    "CommandConfig",
    "CommandManager",
    "Config",
    "ContextOptimizer",
    "ContextWindow",
    "ConversationManager",
    "CustomCommandManager",
    "CustomToolManager",
    "DatabaseManager",
    "DiffTool",
    "DockerManager",
    "DocumentationGenerator",
    "EnvManager",
    "FileOperationCache",
    "FileWatcher",
    "FormatterManager",
    "GitContext",
    "HistorySearch",
    "LSPManager",
    "Logger",
    "MCPClient",
    "MCPManager",
    "MCPServerConfig",
    "Memory",
    "MentionParser",
    "PerformanceMonitor",
    "PerformanceProfiler",
    "PlanApproval",
    "PluginBase",
    "PluginManager",
    "ProjectInitializer",
    "RetryHandler",
    "SearchReplace",
    "SecurityAuditor",
    "SessionManager",
    "ShareManager",
    "ShellExpander",
    "ShellSession",
    "SkillManager",
    "SlashCommandManager",
    "StreamingOutput",
    "TaskQueue",
    "ThemeManager",
    "ToolExecutor",
    "ToolTimeout",
    "TuiConfig",
    "UndoManager",
    "WorkspaceContext",
    "WorkspaceManager",
    "WorkspaceValidator",
    "agent_manager",
    "apex_config",
    "commands_manager",
    "custom_tool_manager",
    "formatter_manager",
    "get_command_manager",
    "get_env_manager",
    "get_file_cache",
    "get_file_completer",
    "get_history_search",
    "get_lsp_manager",
    "get_mention_parser",
    "get_project_initializer",
    "get_repo_map",
    "get_retry_handler",
    "get_skill_manager",
    "get_slash_command_manager",
    "get_task_queue",
    "load_custom_tools",
    "load_mcp_config",
    "load_plugins_from_config",
    "logger",
    "mcp_manager",
    "perf_monitor",
    "plugin_manager",
    "sandbox",
    "share_manager",
    "theme_manager",
    "tui_config",
    "watcher",
    "workspace_manager",
]
