class ApexAi < Formula
  desc "Universal AI coding agent — every model, one terminal"
  homepage "https://apex-ai.dev"
  url "https://github.com/Ggboykxz/APEX/archive/refs/tags/v1.0.0.tar.gz"
  # SHA256 will be auto-generated by `brew audit` or calculated after first release
  # Run: sha256sum /path/to/v1.0.0.tar.gz  and replace below
  sha256 "PLACEHOLDER_SHA256"
  license "MIT"
  head "https://github.com/Ggboykxz/APEX.git", branch: "main"

  depends_on "python@3.12"

  resource "apex-ai" do
    url "https://pypi.org/packages/source/a/apex-ai/apex-ai-1.0.0.tar.gz"
    sha256 "PLACEHOLDER_SHA256"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "1.0.0", shell_output("#{bin}/apex --version 2>&1", 0)
  end
end
